### ISSUE TITLE
не хватает директории desktop.blocks

### ISSUE THREAD

**Issue by belozer** [tadatuta/bem-bemtree-static-project-stub#2]
При запуске проекта можно получить ошибку

```
Error: ENOENT, no such file or directory '/home/sergey/sandbox/bem-bemtree-static-project-stub/desktop.blocks'
```

думаю лучше было бы её добавить в репозиторий изначально.

Или это сделано специально так?

**Comment by tadatuta** [comment]
Спасибо, добавил: https://github.com/tadatuta/bem-bemtree-static-project-stub/commit/fe407f7de536137a84f98b840ec1a77104d9b3c1
