### ISSUE TITLE
*.js

### ISSUE THREAD

**Issue by mirotincev** [tadatuta/bem-bemtree-static-project-stub#5]
Владимир, спасибо за bemtree и работу что вы делаете
Не могли бы еще добавить как работает инициализация js? сколько не пробывал не получается сделать на блок простого вывода алерта при наведении или клика по блоку, когда сам js есть в скомпилированном файле и выводит `console.log(this.name)` но далее `provide(BEMDOM.decl(` ни чего не работет

Заранее спасибо

**Comment by tadatuta** [comment]
@mirotincev Возможно, не хватает поля `js: true` в BEMJSON?

Вообще о том, как работает i-bem.js, написано достаточно подробно в [Руководстве](https://ru.bem.info/technology/i-bem/v2/i-bem-js/), а минимальный работающий пример выглядит так (на основе `project-stub`):
1. В `desktop.bundles/index/index.bemjson.js` создать блок, к которому будет написан JS, например, `{ block: 'b1', js: true, content: 'Кликни меня!' }`. Поле `js: true` с помощью шаблонов сгенерирует на DOM-узле блока микс с блоком `i-bem` и добавить `data-bem` атрибуты.
2. В `common.blocks/b1/b1.js` написать, например, такой код:

``` js
modules.define('b1', ['i-bem__dom'], function(provide, BEMDOM) {

provide(BEMDOM.decl(this.name, {
    onSetMod: {
        js: {
            inited: function() {
                this.bindTo('click', function() {
                    console.log('На меня кликнули')
                });
            }
        }
    }
}));

});
```

Этого должно быть достаточно, чтобы блок начал реагировать на клики.

**Comment by mirotincev** [comment]
@tadatuta Спасибо за ответ,
Сделал тестовый репозиторий, https://github.com/mirotincev/project-stub
Я честно уже не понимаю, запустил bem + hapijs а просто отследить клик не получается
Какой то ступор.

**Comment by mirotincev** [comment]
Спасибо огромное, до меня сейчас только дошло что я пытался сделать что то с элементом блока и не с самим блоком, т.е в моем варианте было `{ block: 'b1', elem:'item', js: true, content: 'Кликни меня!' }` а в js соотвественно

``` javascript
modules.define('b1__item', ['i-bem__dom'], function(provide, BEMDOM) {

provide(BEMDOM.decl(this.name, {
    onSetMod: {
        js: {
            inited: function() {
                this.bindTo('click', function() {
                    console.log('На меня кликнули')
                });
            }
        }
    }
}));

});
```

И у меня ни чего не работало, еще раз спасибо.
PS:Думаю можно закрывать
