### ISSUE TITLE
Сделать контентом формат json

### ISSUE THREAD

**Issue by alexbaumgertner** [tadatuta/bem-bemtree-static-project-stub#6]
Для максимального приближения к реальным условаиям можно сделать исходный формат для контента `json`.

Получится, в папке с блоком будет лежать `block.json` и схема рендеринга выглядит так:
JSON + BEMTREE = BEMJSON
BEMJSON + BEMTREE = HTML

Так же, как и в настоящих проектах.

**Comment by olegdenisov** [comment]
попробовал запустить stub c gulp, не запустился, ругнулся на Error: listen EADDRINUSE 0.0.0.0:8080

**Comment by tadatuta** [comment]
@c1n1k что как бы намекает, что какой-то другой сервер уже занял порт `8080` ;)

**Comment by olegdenisov** [comment]
да, извините, затупил, как менять порт в enb? я что-то не нашёл.
